FROM docker.io/library/node:24-slim AS deps

WORKDIR /app

COPY package.json package-lock.json ./
COPY scripts/prepare-hooks.mjs ./scripts/prepare-hooks.mjs
COPY packages/common/package.json ./packages/common/package.json
COPY apps/mcp-server/package.json ./apps/mcp-server/package.json

RUN npm ci --omit=dev --workspace=mcp-server

FROM docker.io/library/node:24-slim AS runner

WORKDIR /app/apps/mcp-server

COPY --from=deps /app/node_modules /app/node_modules

COPY packages/common /app/packages/common
COPY apps/mcp-server/package.json ./
COPY apps/mcp-server/src ./src

ENV NODE_ENV=production

EXPOSE 5050

CMD ["npm", "run", "prod"]
