FROM node:24-slim AS deps

WORKDIR /app

COPY package.json package-lock.json ./
COPY packages/common/package.json ./packages/common/package.json
COPY apps/a2a-server/package.json ./apps/a2a-server/package.json

RUN npm ci --omit=dev --workspace=a2a-server

FROM node:24-slim AS runner

WORKDIR /app/apps/a2a-server

COPY --from=deps /app/node_modules /app/node_modules

COPY packages/common /app/packages/common
COPY apps/a2a-server/package.json ./
COPY apps/a2a-server/src ./src

ENV NODE_ENV=production

# HTTP port
EXPOSE 4000
# gRPC port
EXPOSE 4001

CMD ["npm", "run", "prod"]
